### Numpy

In [1]:
import numpy as np

In [9]:
# List로 만들기
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
# 배열의 크기
arr1.shape

(5,)

In [11]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]

arr1 = np.array(data2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr1.shape

(2, 4)

In [13]:
# 0으로 구성된 1차원 array 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# 1로 구성된 1차원 array 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# 특성 숫자 (10)으로 구성된 array 생성
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [23]:
# 해상도 : 1920 X 1080
a = np.zeros((30, 3, 1920, 1080))
a

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0.

In [24]:
a.shape

(30, 3, 1920, 1080)

---
### 연산

In [25]:
arr1 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2 = np.array(
    [
        [7,8,9],
        [10,11,12]
    ]
)
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# 덧셈
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [28]:
# arr1을 2배 키우기
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
# arr1의 제곱근 구하기
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Data Handling

In [30]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# index가 5인 데이터 불러오기
arr[5]

5

In [32]:
# arr의 처음부터 4번 index의 데이터 불러오기
arr[:4+1]

array([0, 1, 2, 3, 4])

---
### 2차원 배열

In [33]:
arr2d = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
    ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [40]:
arr2d[1:2+1,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [44]:
arr2d[:,[0,1]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [47]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
arr2d[:1+1,1:2+1] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
### 배열 차원 변경

In [52]:
arr = np.arange(1, 8+1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2))
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])